CREATE TABLE EMPLOYEE1(EMPNO INT,ENAME VARCHAR(50),JOB VARCHAR(50),SALARY MONEY,DEPTNO INT)

SELECT * FROM EMPLOYEE1

GROUPBY:
SELECT JOB,COUNT(*)NUMBEROFEMPLOYEES FROM EMPLOYEE1 GROUP BY JOB
SELECT JOB,COUNT(*)NUMBEROFEMPLOYEES,DEPTNO FROM EMPLOYEE1 GROUP BY JOB,DEPTNO
SELECT JOB,SUM(SALARY)NUMBEROFEMPLOYEES FROM EMPLOYEE1 GROUP BY JOB
SELECT JOB,MAX(SALARY)MAXIMUM,MIN(SALARY)MINIMUM,AVG(SALARY)AVERAGE FROM EMPLOYEE1 GROUP BY JOB
HAVING:
SELECT JOB,COUNT(*)NUMBEROFEMPLOYEES FROM EMPLOYEE1 GROUP BY JOB HAVING COUNT(*)<4
SELECT JOB,SUM(SALARY) FROM EMPLOYEE1 GROUP BY JOB HAVING SUM(SALARY)>10000
ROLLUP:
SELECT JOB,COUNT(*)NUMBEROEPMLOYEES FROM EMPLOYEE1 GROUP BY  ROLLUP(JOB)
SELECT JOB,COUNT(*)NUMBEROEPMLOYEES,DEPTNO FROM EMPLOYEE1 GROUP BY  ROLLUP(JOB,DEPTNO)
CUBE:
SELECT JOB,COUNT(*)NUMBEROEPMLOYEES FROM EMPLOYEE1 GROUP BY  CUBE(JOB)
SELECT JOB,COUNT(*)NUMBEROEPMLOYEES,DEPTNO FROM EMPLOYEE1 GROUP BY  CUBE(JOB,DEPTNO)
