CREATE TABLE STUDENT(STID INT,SNAME VARCHAR (50),SMAILID VARCHAR(40),COURSEID INT)

SELECT *FROM STUDENT

CREATE TABLE COURSE(COURSEID INT,CNAME VARCHAR(40),CFEE DECIMAL(6,2))

SELECT *FROM STUDENT
SELECT * FROM COURSE

SELECT * FROM STUDENT INNER JOIN COURSE ON STUDENT.COURSEID=COURSE.COURSEID

SELECT * FROM STUDENT LEFT OUTER JOIN COURSE ON STUDENT.COURSEID=COURSE.COURSEID

SELECT * FROM STUDENT RIGHT OUTER JOIN COURSE ON STUDENT.COURSEID=COURSE.COURSEID


SELECT * FROM STUDENT FULL OUTER JOIN COURSE ON STUDENT.COURSEID=COURSE.COURSEID

SELECT * FROM STUDENT CROSS JOIN COURSE

STEP2:
SELECT * FROM EMPLOYEE

SELECT * FROM EMPLOYEE WHERE SALARY=85000

SELECT * FROM EMPLOYEE E1,EMPLOYEE E2 WHERE E1.SALARY=E2.SALARY AND E2.ENAME='ADAMS'