
STEP1:
CREATE TABLE DEPARTMENT(DEPTNO INT PRIMARY KEY,DNAME VARCHAR(40),LOCATION VARCHAR(40))----PARENT TABLE

INSERT INTO DEPARTMENT VALUES(10,'DBA','MUMBAI'),(20,'HR','PUNE')
INSERT INTO DEPARTMENT VALUES (30,'SAP','MUMBAI')

SELECT * FROM DEPARTMENT
STEP2:
CREATE TABLE EMPLOYEE(EID INT ,ENAME VARCHAR(50),SALARY MONEY,DEPTNO INT FOREIGN KEY REFERENCES DEPARTMENT(DEPTNO))----CHILD TABLE

SELECT * FROM DEPARTMENT
SELECT * FROM EMPLOYEE
 
INSERT INTO EMPLOYEE VALUES(101,'ADAMS',85000,10)
INSERT INTO EMPLOYEE VALUES(102,'JAMES',45000,20)
INSERT INTO EMPLOYEE VALUES(103,'SCOTT',2300,30)
INSERT INTO EMPLOYEE VALUES(104,'MILLAR',40)---NOT ALLOWED

 SELECT * FROM EMPLOYEE