SELECT * FROM EMP_HYD
SELECT * FROM EMP_CHENNAI


SELECT * FROM EMP_HYD
UNION
SELECT * FROM EMP_CHENNAI

SELECT EID,ENAME FROM EMP_HYD
UNION----ALLOWED
SELECT EID ,ENAME FROM EMP_CHENNAI

SELECT EID,ENAME FROM EMP_HYD
UNION----NOT ALLOWED
SELECT ENAME,EID FROM EMP_CHENNAI

SELECT * FROM EMP_HYD
UNION ALL
SELECT * FROM EMP_CHENNAI

SELECT * FROM EMP_HYD
INTERSECT
SELECT * FROM EMP_CHENNAI

SELECT * FROM EMP_HYD EXCEPT SELECT * FROM EMP_CHENNAI
SELECT * FROM EMP_CHENNAI EXCEPT SELECT * FROM EMP_HYD