


CREATE TABLE COURSE(COURSEID INT,CNAME VARCHAR(40),CFEE DECIMAL(6,2))

SELECT *FROM STUDENT
SELECT *FROM COURSE

SELECT *FROM COURSE INNER JOIN STUDENT ON STUDENT.COURSEID=COURSE.COURSEID

SELECT *FROM STUDENT S LEFT JOIN COURSE C ON S.COURSEID=C.COURSEID

SELECT *FROM STUDENT S RIGHT JOIN COURSE C ON S.COURSEID=C.COURSEID

SELECT *FROM STUDENT S FULL JOIN COURSE C ON S.COURSEID=C.COURSEID