
SELECT * FROM EMPLOYEE

ALTER TABLE EMP ALTER COLUMN ENAME  VARCHAR(20)
ALTER TABLE EMP ADD DEPTNAME VARCHAR(50)

SP_RENAME 'EMP.ENAME','EMPLOYEENAME'

SP_RENAME 'EMP','EMPLOYEE2'

SELECT * FROM EMPLOYEE2

ALTER TABLE EMPLOYEE2 DROP COLUMN DEPTNAME

INSERT INTO EMPLOYEE2(EID,EMPLOYEENAME,SALARY,DEPTNO)VALUES(107,'MALLI',50000,70)

UPDATE EMPLOYEE2 SET EID=107 WHERE EID=108
UPDATE EMPLOYEE2 SET SALARY=35000 WHERE SALARY IS NULL

DELETE FROM EMPLOYEE2 WHERE EID=107

TRUNCATE TABLE TEST2

SELECT EID,EMPLOYEENAME,SALARY FROM EMPLOYEE2

SELECT * FROM EMPLOYEE2 WHERE EID=101

SELECT  EID ,EMPLOYEENAME FROM EMPLOYEE2 WHERE EID=101

UPDATE EMPLOYEE2 SET SALARY=45000 WHERE EID=107

ALTER TABLE EMPLOYEE2 ADD ADDRESS VARCHAR(50)


SELECT * FROM EMPLOYEE2

ALTER TABLE EMPLOYEE2 DROP COLUMN ASDRESS

UPDATE EMPLOYEE2 SET ADDRESS='GOLLALADODDI'

SP_RENAME 'EMPLOYEE2.ADDRESS','DEPTNAME'

SP_RENAME 'EMP','HOSPITAL'

SELECT * FROM HOSPITAL

ALTER TABLE HOSPITAL DROP COLUMN DEPTNAME 

SP_RENAME 'HOSPITAL.EID','DEPTID'

SP_RENAME 'HOSPITAL','DEPARTMENT1'
SELECT * FROM DEPARTMENT1