
SELECT * FROM EMP

SINGLE ROW_SUBQUERY:
STEP1:
INNERQUERY:
SELECT MAX(SALARY)FROM EMP;
STEP2:
OUTERQUERY:
SELECT *FROM EMP WHERE SALARY=(INNERQUERY)
STEP3:
SUBQUERY=INNERQUERY+OUTERQUERY:

SELECT * FROM EMP WHERE SALARY=(SELECT MAX(SALARY)FROM EMP)

MULTIPLE ROW_SUBQUERY:
SELECT * FROM EMP WHERE DEPTNAME IN (SELECT DEPTNAME FROM EMP WHERE ENAME IN ('SMITH','SCOTT'))

