select * from EMPLOYEE1


CREATE TABLE EMP(EID INT,ENAME VARCHAR(50),SALARY MONEY,DEPTNAME VARCHAR(50))

SELECT * FROM EMP

CREATE FUNCTION TVF1(@DEPTNAME VARCHAR(40))
RETURNS TABLE
AS
RETURN(SELECT * FROM EMP WHERE DEPTNAME=@DEPTNAME)


SELECT * FROM TVF1('.NET')